openapi: 3.0.1
info:
  contact:
    email: edeutsch@systemsbiology.org
  description: OpenAPI for NCATS Biomedical Translator Reasoners
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: OpenAPI for NCATS Biomedical Translator Reasoners
  version: 0.9.0
externalDocs:
  description: Documentation for the NCATS Biomedical Translator Reasoners web services
  url: https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI
servers:
- url: /
tags:
- description: Query reasoner using a predefined question type
  externalDocs:
    description: Documentation for the reasoner query function
    url: http://reasonerhost.ncats.io/overview.html#query
  name: query
- description: Request stored messages and feedback for messages
  externalDocs:
    description: Documentation for the reasoner message function
    url: https://reasonerhost.ncats.io/overview.html#message
  name: message
- description: Request stored results and feedback for results
  externalDocs:
    description: Documentation for the reasoner result function
    url: http://reasonerhost.ncats.io/overview.html#result
  name: result
paths:
  /feedback/all:
    get:
      operationId: get_feedback_all
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Feedback'
                type: array
          description: successful operation
      summary: Request a list of all feedback provided thus far
      tags:
      - feedback
      x-swagger-router-controller: swagger_server.controllers.feedback_controller
      x-openapi-router-controller: openapi_server.controllers.feedback_controller
  /feedback/expertise_levels:
    get:
      operationId: get_feedback_expertise_levels
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpertiseLevels'
          description: successful operation
      summary: Request a list of allowable expertise levels
      tags:
      - feedback
      x-swagger-router-controller: swagger_server.controllers.feedback_controller
      x-openapi-router-controller: openapi_server.controllers.feedback_controller
  /feedback/ratings:
    get:
      operationId: get_feedback_ratings
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ratings'
          description: successful operation
      summary: Request a list of allowable ratings
      tags:
      - feedback
      x-swagger-router-controller: swagger_server.controllers.feedback_controller
      x-openapi-router-controller: openapi_server.controllers.feedback_controller
  /message/{message_id}:
    get:
      operationId: get_message
      parameters:
      - description: Integer identifier of the message to return
        explode: false
        in: path
        name: message_id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: successful operation
        404:
          description: Message_id not found
      summary: Request stored messages and results from reasoner
      tags:
      - message
      x-swagger-router-controller: swagger_server.controllers.message_controller
      x-openapi-router-controller: openapi_server.controllers.message_controller
  /message/{message_id}/feedback:
    get:
      operationId: get_message_feedback
      parameters:
      - description: Integer identifier of the message to return
        explode: false
        in: path
        name: message_id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageFeedback'
          description: successful operation
        404:
          description: Message_id not found
      summary: Request stored feedback for this message from reasoner
      tags:
      - message
      x-swagger-router-controller: swagger_server.controllers.message_controller
      x-openapi-router-controller: openapi_server.controllers.message_controller
  /query:
    post:
      operationId: query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
        description: Query information to be submitted
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: successful operation
        400:
          description: Invalid status value
      summary: Query reasoner via one of several inputs
      tags:
      - query
      x-swagger-router-controller: swagger_server.controllers.query_controller
      x-openapi-router-controller: openapi_server.controllers.query_controller
  /result/{result_id}:
    get:
      operationId: get_result
      parameters:
      - description: Integer identifier of the result to return
        explode: false
        in: path
        name: result_id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
          description: successful operation
        404:
          description: result_id not found
      summary: Request stored result
      tags:
      - result
      x-swagger-router-controller: swagger_server.controllers.result_controller
      x-openapi-router-controller: openapi_server.controllers.result_controller
  /result/{result_id}/feedback:
    get:
      operationId: get_result_feedback
      parameters:
      - description: Integer identifier of the result to return
        explode: false
        in: path
        name: result_id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultFeedback'
          description: successful operation
        404:
          description: result_id not found
      summary: Request stored feedback for this result
      tags:
      - result
      x-swagger-router-controller: swagger_server.controllers.result_controller
      x-openapi-router-controller: openapi_server.controllers.result_controller
    post:
      operationId: post_result_feedback
      parameters:
      - description: Integer identifier of the result to return
        explode: false
        in: path
        name: result_id
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Feedback'
        description: Comment information
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedbackResponse'
          description: successful operation
        400:
          description: Invalid status value
      summary: Store feedback for a particular result
      tags:
      - result
      x-swagger-router-controller: swagger_server.controllers.result_controller
      x-openapi-router-controller: openapi_server.controllers.result_controller
components:
  schemas:
    FeedbackResponse:
      example:
        detail: detail
        title: title
        type: type
        status: 0
      properties:
        detail:
          type: string
        status:
          type: integer
        title:
          type: string
        type:
          type: string
      type: object
    Ratings:
      example:
        n_ratings: 1
        ratings:
        - score: 6.027456183070403
          rating_id: 0
          name: name
          description: description
          tag: tag
        - score: 6.027456183070403
          rating_id: 0
          name: name
          description: description
          tag: tag
      properties:
        ratings:
          items:
            $ref: '#/components/schemas/Rating'
          type: array
        n_ratings:
          type: integer
      type: object
    Rating:
      example:
        score: 6.027456183070403
        rating_id: 0
        name: name
        description: description
        tag: tag
      properties:
        description:
          type: string
        rating_id:
          type: integer
        name:
          type: string
        score:
          type: number
        tag:
          type: string
      type: object
    ExpertiseLevels:
      example:
        n_expertise_levels: 1
        expertise_levels:
        - score: 6.027456183070403
          expertise_level_id: 0
          name: name
          description: description
          tag: tag
        - score: 6.027456183070403
          expertise_level_id: 0
          name: name
          description: description
          tag: tag
      properties:
        expertise_levels:
          items:
            $ref: '#/components/schemas/ExpertiseLevel'
          type: array
        n_expertise_levels:
          type: integer
      type: object
    ExpertiseLevel:
      example:
        score: 6.027456183070403
        expertise_level_id: 0
        name: name
        description: description
        tag: tag
      properties:
        description:
          type: string
        expertise_level_id:
          type: integer
        name:
          type: string
        score:
          type: number
        tag:
          type: string
      type: object
    Query:
      additionalProperties: true
      properties:
        bypass_cache:
          description: Set to true in order to bypass any possible cached message
            and try to answer the query over again
          example: "true"
          type: string
        asynchronous:
          description: Set to true in order to receive an incomplete message_id if
            the query will take a while. Client can then periodically request that
            message_id for a status update and eventual complete message
          example: "false"
          type: string
        max_results:
          description: Maximum number of individual results to return
          example: 100
          type: integer
        page_size:
          description: Split the results into pages with this number of results each
          example: 20
          type: integer
        page_number:
          description: Page number of results when the number of results exceeds the
            page_size
          example: 1
          type: integer
        reasoner_ids:
          description: List of reasoners to consult for the query
          example:
          - RTX
          - Robokop
          items:
            type: string
          type: array
        query_message:
          description: Message object that represents the query to be answered
          items:
            $ref: '#/components/schemas/Message'
          type: object
        previous_message_processing_plan:
          description: Container for one or more Message objects or identifiers for
            one or more Messages along with a processing plan for how those messages
            should be processed and returned
          items:
            $ref: '#/components/schemas/PreviousMessageProcessingPlan'
          type: object
      type: object
      x-body-name: request_body
    PreviousMessageProcessingPlan:
      additionalProperties: true
      properties:
        previous_message_uris:
          description: List of URIs for Message objects to fetch and process
          example:
          - https://rtx.ncats.io/api/rtx/v1/message/300
          items:
            type: string
          type: array
        previous_messages:
          description: List of Message objects to process
          items:
            $ref: '#/components/schemas/Message'
          type: array
        processing_actions:
          description: List of order-dependent actions to guide what happens with
            the Message object(s)
          example:
          - mod45filter
          - redirect2RTX
          items:
            type: string
          type: array
        options:
          additionalProperties: true
          description: Dict of options that apply during processing in an order independent
            fashion
          example:
            topNMostFrequent: 1
          type: object
      type: object
    Message:
      additionalProperties: true
      example:
        original_question: what proteins are affected by sickle cell anemia
        query_options:
          coalesce: true
          threshold: 0.9
        n_results: 42
        restated_question: Which proteins are affected by sickle cell anemia?
        code_description: 9 results found
        type: translator_reasoner_message
        knowledge_graph: '{}'
        query_type_id: Q2
        query_graph:
          nodes:
          - curie: OMIM:603903
            type: disease
            node_id: n00
          - curie: OMIM:603903
            type: disease
            node_id: n00
          edges:
          - negated: true
            edge_id: e00
            target_id: https://www.uniprot.org/uniprot/P00738
            source_id: https://omim.org/entry/603903
            type: affects
            relation: upregulates
          - negated: true
            edge_id: e00
            target_id: https://www.uniprot.org/uniprot/P00738
            source_id: https://omim.org/entry/603903
            type: affects
            relation: upregulates
        schema_version: 0.9.0
        datetime: 2018-01-09 12:34:45
        table_column_names:
        - chemical_substance.name
        - chemical_substance.id
        tool_version: RTX 0.5.0
        message_code: OK
        terms:
          anatomical_entity: liver
          disease: malaria
          metabolite: ibuprofen
          protein: P12345
          chemical_substance: ibuprofen
        context: https://rtx.ncats.io/ns/translator.jsonld
        reasoner_id: reasoner
        id: https://rtx.ncats.io/api/rtx/v1/message/123
        results:
        - result_type: individual query answer
          result_graph:
            nodes:
            - symbol: HP
              node_attributes:
              - name: Wikipedia article
                type: article
                value: 7.23e-12
                url: https://en.wikipedia.org/wiki/Malaria
              - name: Wikipedia article
                type: article
                value: 7.23e-12
                url: https://en.wikipedia.org/wiki/Malaria
              name: Haptoglobin
              description: Haptoglobin captures, and combines with free plasma hemoglobin...
              id: OMIM:603903
              type:
              - protein
              uri: https://www.uniprot.org/uniprot/P00738
            - symbol: HP
              node_attributes:
              - name: Wikipedia article
                type: article
                value: 7.23e-12
                url: https://en.wikipedia.org/wiki/Malaria
              - name: Wikipedia article
                type: article
                value: 7.23e-12
                url: https://en.wikipedia.org/wiki/Malaria
              name: Haptoglobin
              description: Haptoglobin captures, and combines with free plasma hemoglobin...
              id: OMIM:603903
              type:
              - protein
              uri: https://www.uniprot.org/uniprot/P00738
            edges:
            - negated: true
              evidence_type: ECO:0000220
              defined_datetime: 2018-11-03 15:34:23
              confidence: 0.99
              weight: 0.99
              qualifiers: ECO:0000220
              target_id: https://www.uniprot.org/uniprot/P00738
              type: affects
              relation: upregulates
              is_defined_by: reasoner
              edge_attributes:
              - name: Cell type limitation
                type: localization
                value: MFC cells
                url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
              - name: Cell type limitation
                type: localization
                value: MFC cells
                url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
              provided_by: OMIM
              id: "553903"
              source_id: https://omim.org/entry/603903
              publications:
              - PMID:12345562
            - negated: true
              evidence_type: ECO:0000220
              defined_datetime: 2018-11-03 15:34:23
              confidence: 0.99
              weight: 0.99
              qualifiers: ECO:0000220
              target_id: https://www.uniprot.org/uniprot/P00738
              type: affects
              relation: upregulates
              is_defined_by: reasoner
              edge_attributes:
              - name: Cell type limitation
                type: localization
                value: MFC cells
                url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
              - name: Cell type limitation
                type: localization
                value: MFC cells
                url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
              provided_by: OMIM
              id: "553903"
              source_id: https://omim.org/entry/603903
              publications:
              - PMID:12345562
          essence: ibuprofen
          confidence: 0.9234
          description: The genetic condition sickle cell anemia may provide protection
            from cerebral malaria via genetic alterations of proteins HBB (P68871)
            and HMOX1 (P09601).
          essence_type: drug
          score_direction: lower_is_better
          score: 163.233
          edge_bindings:
            key: ""
          result_group: 1
          reasoner_id: RTX
          node_bindings:
            key: ""
          id: https://rtx.ncats.io/api/rtx/v1/result/234
          row_data:
          - ibuprofen
          - CHEMBL:CHEMBL521
          result_group_similarity_score: 0.95
          score_name: Jaccard distance
        - result_type: individual query answer
          result_graph:
            nodes:
            - symbol: HP
              node_attributes:
              - name: Wikipedia article
                type: article
                value: 7.23e-12
                url: https://en.wikipedia.org/wiki/Malaria
              - name: Wikipedia article
                type: article
                value: 7.23e-12
                url: https://en.wikipedia.org/wiki/Malaria
              name: Haptoglobin
              description: Haptoglobin captures, and combines with free plasma hemoglobin...
              id: OMIM:603903
              type:
              - protein
              uri: https://www.uniprot.org/uniprot/P00738
            - symbol: HP
              node_attributes:
              - name: Wikipedia article
                type: article
                value: 7.23e-12
                url: https://en.wikipedia.org/wiki/Malaria
              - name: Wikipedia article
                type: article
                value: 7.23e-12
                url: https://en.wikipedia.org/wiki/Malaria
              name: Haptoglobin
              description: Haptoglobin captures, and combines with free plasma hemoglobin...
              id: OMIM:603903
              type:
              - protein
              uri: https://www.uniprot.org/uniprot/P00738
            edges:
            - negated: true
              evidence_type: ECO:0000220
              defined_datetime: 2018-11-03 15:34:23
              confidence: 0.99
              weight: 0.99
              qualifiers: ECO:0000220
              target_id: https://www.uniprot.org/uniprot/P00738
              type: affects
              relation: upregulates
              is_defined_by: reasoner
              edge_attributes:
              - name: Cell type limitation
                type: localization
                value: MFC cells
                url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
              - name: Cell type limitation
                type: localization
                value: MFC cells
                url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
              provided_by: OMIM
              id: "553903"
              source_id: https://omim.org/entry/603903
              publications:
              - PMID:12345562
            - negated: true
              evidence_type: ECO:0000220
              defined_datetime: 2018-11-03 15:34:23
              confidence: 0.99
              weight: 0.99
              qualifiers: ECO:0000220
              target_id: https://www.uniprot.org/uniprot/P00738
              type: affects
              relation: upregulates
              is_defined_by: reasoner
              edge_attributes:
              - name: Cell type limitation
                type: localization
                value: MFC cells
                url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
              - name: Cell type limitation
                type: localization
                value: MFC cells
                url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
              provided_by: OMIM
              id: "553903"
              source_id: https://omim.org/entry/603903
              publications:
              - PMID:12345562
          essence: ibuprofen
          confidence: 0.9234
          description: The genetic condition sickle cell anemia may provide protection
            from cerebral malaria via genetic alterations of proteins HBB (P68871)
            and HMOX1 (P09601).
          essence_type: drug
          score_direction: lower_is_better
          score: 163.233
          edge_bindings:
            key: ""
          result_group: 1
          reasoner_id: RTX
          node_bindings:
            key: ""
          id: https://rtx.ncats.io/api/rtx/v1/result/234
          row_data:
          - ibuprofen
          - CHEMBL:CHEMBL521
          result_group_similarity_score: 0.95
          score_name: Jaccard distance
      properties:
        context:
          description: JSON-LD context URI
          example: https://rtx.ncats.io/ns/translator.jsonld
          type: string
        type:
          description: Entity type of this message
          example: translator_reasoner_message
          type: string
        id:
          description: URI for this message
          example: https://rtx.ncats.io/api/rtx/v1/message/123
          type: string
        reasoner_id:
          description: Identifier string of the reasoner that provided this message
            (one of RTX, Robokop, Indigo, Integrator, etc.)
          example: reasoner
          type: string
        tool_version:
          description: Version label of the tool that generated this message
          example: RTX 0.5.0
          type: string
        schema_version:
          description: Version label of this JSON-LD schema
          example: 0.9.0
          type: string
        datetime:
          description: Datetime string for the time that this message was generated
          example: 2018-01-09 12:34:45
          type: string
        n_results:
          description: Total number of results from the query (which may be less than
            what is returned if limits were placed on the number of results to return)
          example: 42
          type: integer
        message_code:
          description: Set to OK for success, or some other short string to indicate
            and error (e.g., KGUnavailable, TermNotFound, etc.)
          example: OK
          type: string
        code_description:
          description: Extended description denoting the success or mode of failure
            in the generation of the message
          example: 9 results found
          type: string
        table_column_names:
          description: List of column names that corresponds to the row_data for each
            result
          example:
          - chemical_substance.name
          - chemical_substance.id
          items:
            type: string
          type: array
        original_question:
          description: The original question text typed in by the user
          example: what proteins are affected by sickle cell anemia
          type: string
        restated_question:
          description: A precise restatement of the question, as understood by the
            Translator, for which the answer applies. The user should verify that
            the restated question matches the intent of their original question (it
            might not).
          example: Which proteins are affected by sickle cell anemia?
          type: string
        query_type_id:
          description: The query type id if one is known for the query/message (as
            defined in https://docs.google.com/spreadsheets/d/18zW81wteUfOn3rFRVG0z8mW-ecNhdsfD_6s73ETJnUw/edit#gid=1742835901
            )
          example: Q2
          type: string
        terms:
          $ref: '#/components/schemas/Message_terms'
        query_options:
          description: Dict of options that can be sent with the query. Options are
            tool specific and not stipulated here
          example:
            coalesce: true
            threshold: 0.9
          type: object
        results:
          description: List of all returned potential answers for the query posed
          items:
            $ref: '#/components/schemas/Result'
          type: array
        query_graph:
          $ref: '#/components/schemas/QueryGraph'
        knowledge_graph:
          description: KnowledgeGraph object that contains all the nodes and edges
            referenced in any of the possible answers to the query OR connection information
            for a remote knowledge graph
          oneOf:
          - $ref: '#/components/schemas/KnowledgeGraph'
          - $ref: '#/components/schemas/RemoteKnowledgeGraph'
          type: object
      type: object
    Result:
      description: One of potentially several results or answers for a query
      example:
        result_type: individual query answer
        result_graph:
          nodes:
          - symbol: HP
            node_attributes:
            - name: Wikipedia article
              type: article
              value: 7.23e-12
              url: https://en.wikipedia.org/wiki/Malaria
            - name: Wikipedia article
              type: article
              value: 7.23e-12
              url: https://en.wikipedia.org/wiki/Malaria
            name: Haptoglobin
            description: Haptoglobin captures, and combines with free plasma hemoglobin...
            id: OMIM:603903
            type:
            - protein
            uri: https://www.uniprot.org/uniprot/P00738
          - symbol: HP
            node_attributes:
            - name: Wikipedia article
              type: article
              value: 7.23e-12
              url: https://en.wikipedia.org/wiki/Malaria
            - name: Wikipedia article
              type: article
              value: 7.23e-12
              url: https://en.wikipedia.org/wiki/Malaria
            name: Haptoglobin
            description: Haptoglobin captures, and combines with free plasma hemoglobin...
            id: OMIM:603903
            type:
            - protein
            uri: https://www.uniprot.org/uniprot/P00738
          edges:
          - negated: true
            evidence_type: ECO:0000220
            defined_datetime: 2018-11-03 15:34:23
            confidence: 0.99
            weight: 0.99
            qualifiers: ECO:0000220
            target_id: https://www.uniprot.org/uniprot/P00738
            type: affects
            relation: upregulates
            is_defined_by: reasoner
            edge_attributes:
            - name: Cell type limitation
              type: localization
              value: MFC cells
              url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
            - name: Cell type limitation
              type: localization
              value: MFC cells
              url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
            provided_by: OMIM
            id: "553903"
            source_id: https://omim.org/entry/603903
            publications:
            - PMID:12345562
          - negated: true
            evidence_type: ECO:0000220
            defined_datetime: 2018-11-03 15:34:23
            confidence: 0.99
            weight: 0.99
            qualifiers: ECO:0000220
            target_id: https://www.uniprot.org/uniprot/P00738
            type: affects
            relation: upregulates
            is_defined_by: reasoner
            edge_attributes:
            - name: Cell type limitation
              type: localization
              value: MFC cells
              url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
            - name: Cell type limitation
              type: localization
              value: MFC cells
              url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
            provided_by: OMIM
            id: "553903"
            source_id: https://omim.org/entry/603903
            publications:
            - PMID:12345562
        essence: ibuprofen
        confidence: 0.9234
        description: The genetic condition sickle cell anemia may provide protection
          from cerebral malaria via genetic alterations of proteins HBB (P68871) and
          HMOX1 (P09601).
        essence_type: drug
        score_direction: lower_is_better
        score: 163.233
        edge_bindings:
          key: ""
        result_group: 1
        reasoner_id: RTX
        node_bindings:
          key: ""
        id: https://rtx.ncats.io/api/rtx/v1/result/234
        row_data:
        - ibuprofen
        - CHEMBL:CHEMBL521
        result_group_similarity_score: 0.95
        score_name: Jaccard distance
      properties:
        id:
          description: URI for this message
          example: https://rtx.ncats.io/api/rtx/v1/result/234
          type: string
        description:
          description: A free text description of this result answer from the reasoner
          example: The genetic condition sickle cell anemia may provide protection
            from cerebral malaria via genetic alterations of proteins HBB (P68871)
            and HMOX1 (P09601).
          type: string
        essence:
          description: A single string that is the terse essence of the result (useful
            for simple answers)
          example: ibuprofen
          type: string
        essence_type:
          description: A Translator bioentity type of the essence
          example: drug
          type: string
        row_data:
          description: An arbitrary list of values that captures the essence of the
            result that can be turned into a tabular result across all answers (each
            result is a row) for a user that wants tabular output
          example:
          - ibuprofen
          - CHEMBL:CHEMBL521
          items:
            type: string
          type: array
        score:
          description: Any type of score associated with this result
          example: 163.233
          format: float
          type: number
        score_name:
          description: Name for the score
          example: Jaccard distance
          type: string
        score_direction:
          description: 'Sorting indicator for the score: one of higher_is_better or
            lower_is_better'
          example: lower_is_better
          type: string
        confidence:
          description: Confidence metric for this result, a value between (inclusive)
            0.0 (no confidence) and 1.0 (highest confidence)
          example: 0.9234
          format: float
          type: number
        result_type:
          description: 'One of several possible result types: ''individual query answer'',
            ''neighborhood graph'', ''type summary graph'''
          example: individual query answer
          type: string
        result_group:
          description: An integer group number for results for use in cases where
            several results should be grouped together. Also useful to control sorting
            ascending.
          example: 1
          type: integer
        result_group_similarity_score:
          description: A score that denotes the similarity of this result to other
            members of the result_group
          example: 0.95
          format: float
          type: number
        reasoner_id:
          description: Identifier string of the reasoner that provided this result
            (e.g., RTX, Robokop, Indigo, Integrator)
          example: RTX
          type: string
        result_graph:
          $ref: '#/components/schemas/KnowledgeGraph'
        node_bindings:
          additionalProperties:
            oneOf:
            - type: string
            - items:
                type: string
              type: array
          description: Lookup dict that maps QNode identifiers in the QueryGraph to
            Node identifiers in the KnowledgeGraph
          type: object
        edge_bindings:
          additionalProperties:
            oneOf:
            - type: string
            - items:
                type: string
              type: array
          description: Lookup dict that maps QEdge identifiers in the QueryGraph to
            Edge identifiers in the KnowledgeGraph
          type: object
      type: object
    KnowledgeGraph:
      additionalProperties: true
      description: A thought graph associated with this result. This will commonly
        be a linear path subgraph from one concept to another, but related items aside
        of the path may be included.
      example:
        nodes:
        - symbol: HP
          node_attributes:
          - name: Wikipedia article
            type: article
            value: 7.23e-12
            url: https://en.wikipedia.org/wiki/Malaria
          - name: Wikipedia article
            type: article
            value: 7.23e-12
            url: https://en.wikipedia.org/wiki/Malaria
          name: Haptoglobin
          description: Haptoglobin captures, and combines with free plasma hemoglobin...
          id: OMIM:603903
          type:
          - protein
          uri: https://www.uniprot.org/uniprot/P00738
        - symbol: HP
          node_attributes:
          - name: Wikipedia article
            type: article
            value: 7.23e-12
            url: https://en.wikipedia.org/wiki/Malaria
          - name: Wikipedia article
            type: article
            value: 7.23e-12
            url: https://en.wikipedia.org/wiki/Malaria
          name: Haptoglobin
          description: Haptoglobin captures, and combines with free plasma hemoglobin...
          id: OMIM:603903
          type:
          - protein
          uri: https://www.uniprot.org/uniprot/P00738
        edges:
        - negated: true
          evidence_type: ECO:0000220
          defined_datetime: 2018-11-03 15:34:23
          confidence: 0.99
          weight: 0.99
          qualifiers: ECO:0000220
          target_id: https://www.uniprot.org/uniprot/P00738
          type: affects
          relation: upregulates
          is_defined_by: reasoner
          edge_attributes:
          - name: Cell type limitation
            type: localization
            value: MFC cells
            url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
          - name: Cell type limitation
            type: localization
            value: MFC cells
            url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
          provided_by: OMIM
          id: "553903"
          source_id: https://omim.org/entry/603903
          publications:
          - PMID:12345562
        - negated: true
          evidence_type: ECO:0000220
          defined_datetime: 2018-11-03 15:34:23
          confidence: 0.99
          weight: 0.99
          qualifiers: ECO:0000220
          target_id: https://www.uniprot.org/uniprot/P00738
          type: affects
          relation: upregulates
          is_defined_by: reasoner
          edge_attributes:
          - name: Cell type limitation
            type: localization
            value: MFC cells
            url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
          - name: Cell type limitation
            type: localization
            value: MFC cells
            url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
          provided_by: OMIM
          id: "553903"
          source_id: https://omim.org/entry/603903
          publications:
          - PMID:12345562
      properties:
        nodes:
          description: List of nodes in the KnowledgeGraph
          items:
            $ref: '#/components/schemas/Node'
          type: array
        edges:
          description: List of edges in the KnowledgeGraph
          items:
            $ref: '#/components/schemas/Edge'
          type: array
      required:
      - edges
      - nodes
      type: object
    RemoteKnowledgeGraph:
      additionalProperties: true
      description: A thought graph associated with this result that is not repeated
        here, but stored elsewhere in a way that can be remotely accessed by the reader
        of this Message
      properties:
        url:
          description: URL that provides programmatic access to the remote knowledge
            graph
          example: http://robokop.renci.org/api/kg
          type: string
        credentials:
          description: Credentials needed for programmatic access to the remote knowledge
            graph
          items:
            $ref: '#/components/schemas/Credentials'
          type: object
      type: object
    Credentials:
      additionalProperties: true
      description: Credentials needed for programmatic access to the remote knowledge
        graph
      properties:
        username:
          description: Username needed for programmatic access to the remote knowledge
            graph
          type: string
        password:
          description: Password needed for programmatic access to the remote knowledge
            graph
          type: string
      required:
      - password
      - username
      type: object
    QueryGraph:
      additionalProperties: true
      description: A graph intended to be the thought path to be followed by a reasoner
        to answer the question. This graph is a representation of a question.
      example:
        nodes:
        - curie: OMIM:603903
          type: disease
          node_id: n00
        - curie: OMIM:603903
          type: disease
          node_id: n00
        edges:
        - negated: true
          edge_id: e00
          target_id: https://www.uniprot.org/uniprot/P00738
          source_id: https://omim.org/entry/603903
          type: affects
          relation: upregulates
        - negated: true
          edge_id: e00
          target_id: https://www.uniprot.org/uniprot/P00738
          source_id: https://omim.org/entry/603903
          type: affects
          relation: upregulates
      properties:
        nodes:
          description: List of nodes in the QueryGraph
          items:
            $ref: '#/components/schemas/QNode'
          type: array
        edges:
          description: List of edges in the QueryGraph
          items:
            $ref: '#/components/schemas/QEdge'
          type: array
      required:
      - edges
      - nodes
      type: object
    QNode:
      additionalProperties: true
      description: A node in the QueryGraph
      example:
        curie: OMIM:603903
        type: disease
        node_id: n00
      properties:
        node_id:
          description: 'QueryGraph internal identifier for this QNode. Recommended
            form: n00, n01, n02, etc.'
          example: n00
          type: string
        curie:
          description: CURIE identifier for this node
          example: OMIM:603903
          type: string
        type:
          description: Entity type of this node (e.g., protein, disease, etc.)
          example: disease
          type: string
      type: object
    QEdge:
      additionalProperties: true
      description: An edge in the QueryGraph
      example:
        negated: true
        edge_id: e00
        target_id: https://www.uniprot.org/uniprot/P00738
        source_id: https://omim.org/entry/603903
        type: affects
        relation: upregulates
      properties:
        edge_id:
          description: 'QueryGraph internal identifier for this QEdge. Recommended
            form: e00, e01, e02, etc.'
          example: e00
          type: string
        type:
          description: Higher-level relationship type of this edge
          example: affects
          type: string
        relation:
          description: Lower-level relationship type of this edge
          example: upregulates
          type: string
        source_id:
          description: Corresponds to the @id of source node of this edge
          example: https://omim.org/entry/603903
          type: string
        target_id:
          description: Corresponds to the @id of target node of this edge
          example: https://www.uniprot.org/uniprot/P00738
          type: string
        negated:
          description: Boolean that if set to true, indicates the edge statement is
            negated i.e. is not true
          example: true
          type: boolean
      required:
      - source_id
      - target_id
      type: object
    Node:
      additionalProperties: true
      description: A node in the thought subgraph
      example:
        symbol: HP
        node_attributes:
        - name: Wikipedia article
          type: article
          value: 7.23e-12
          url: https://en.wikipedia.org/wiki/Malaria
        - name: Wikipedia article
          type: article
          value: 7.23e-12
          url: https://en.wikipedia.org/wiki/Malaria
        name: Haptoglobin
        description: Haptoglobin captures, and combines with free plasma hemoglobin...
        id: OMIM:603903
        type:
        - protein
        uri: https://www.uniprot.org/uniprot/P00738
      properties:
        id:
          description: CURIE identifier for this node
          example: OMIM:603903
          type: string
        uri:
          description: URI identifier for this node"
          example: https://www.uniprot.org/uniprot/P00738
          type: string
        name:
          description: Formal name of the entity
          example: Haptoglobin
          type: string
        type:
          description: Entity type of this node (e.g., protein, disease, etc.)
          example:
          - protein
          items:
            type: string
          type: array
        description:
          description: One to three sentences of description/definition of this entity
          example: Haptoglobin captures, and combines with free plasma hemoglobin...
          type: string
        symbol:
          description: Short abbreviation or symbol for this entity
          example: HP
          type: string
        node_attributes:
          description: A list of arbitrary attributes for the node
          items:
            $ref: '#/components/schemas/NodeAttribute'
          type: array
      required:
      - id
      type: object
    NodeAttribute:
      additionalProperties: true
      description: A generic attribute for a node
      example:
        name: Wikipedia article
        type: article
        value: 7.23e-12
        url: https://en.wikipedia.org/wiki/Malaria
      properties:
        type:
          description: Entity type of this attribute
          example: article
          type: string
        name:
          description: Formal name of the attribute
          example: Wikipedia article
          type: string
        value:
          description: Value of the attribute
          example: 7.23e-12
          type: string
        url:
          description: A URL corresponding to this attribute
          example: https://en.wikipedia.org/wiki/Malaria
          type: string
      type: object
    Edge:
      additionalProperties: true
      description: An edge in the thought subgraph linking two nodes
      example:
        negated: true
        evidence_type: ECO:0000220
        defined_datetime: 2018-11-03 15:34:23
        confidence: 0.99
        weight: 0.99
        qualifiers: ECO:0000220
        target_id: https://www.uniprot.org/uniprot/P00738
        type: affects
        relation: upregulates
        is_defined_by: reasoner
        edge_attributes:
        - name: Cell type limitation
          type: localization
          value: MFC cells
          url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
        - name: Cell type limitation
          type: localization
          value: MFC cells
          url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
        provided_by: OMIM
        id: "553903"
        source_id: https://omim.org/entry/603903
        publications:
        - PMID:12345562
      properties:
        id:
          description: Local identifier for this node which is unique within this
            KnowledgeGraph, and perhaps within the source reasoner's knowledge graph
          example: "553903"
          type: string
        type:
          description: Higher-level relationship type of this edge
          example: affects
          type: string
        relation:
          description: Lower-level relationship type of this edge
          example: upregulates
          type: string
        source_id:
          description: Corresponds to the @id of source node of this edge
          example: https://omim.org/entry/603903
          type: string
        target_id:
          description: Corresponds to the @id of target node of this edge
          example: https://www.uniprot.org/uniprot/P00738
          type: string
        is_defined_by:
          description: A CURIE/URI for the translator group that made the KG
          example: reasoner
          type: string
        defined_datetime:
          description: Datetime at which the KG builder/updater pulled the information
            from the original source. Used as a freshness indicator.
          example: 2018-11-03 15:34:23
          type: string
        provided_by:
          description: A CURIE/URI for the knowledge source that defined this edge
          example: OMIM
          type: string
        confidence:
          description: Confidence metric for this edge, a value between (inclusive)
            0.0 (no confidence) and 1.0 (highest confidence)
          example: 0.99
          format: float
          type: number
        weight:
          description: Weight metric for this edge, with no upper bound. Perhaps useful
            when formal confidence metrics are not available
          example: 0.99
          format: float
          type: number
        publications:
          description: List of CURIEs for publications associated with this edge
          example:
          - PMID:12345562
          items:
            type: string
          type: array
        evidence_type:
          description: A CURIE/URI for class of evidence supporting the statement
            made in an edge - typically a class from the ECO ontology
          example: ECO:0000220
          type: string
        qualifiers:
          description: Terms representing qualifiers that modify or qualify the meaning
            of the statement made in an edge
          example: ECO:0000220
          type: string
        negated:
          description: Boolean that if set to true, indicates the edge statement is
            negated i.e. is not true
          example: true
          type: boolean
        edge_attributes:
          description: A list of additional attributes for this edge
          items:
            $ref: '#/components/schemas/EdgeAttribute'
          type: array
      required:
      - id
      - source_id
      - target_id
      type: object
    EdgeAttribute:
      additionalProperties: true
      description: A generic additional attribute for an edge
      example:
        name: Cell type limitation
        type: localization
        value: MFC cells
        url: https://www.ncbi.nlm.nih.gov/pubmed/29309293
      properties:
        type:
          description: Entity type of this attribute
          example: localization
          type: string
        name:
          description: Formal name of the attribute
          example: Cell type limitation
          type: string
        value:
          description: Value of the attribute. While all attributes should have a
            name, many will not have a value
          example: MFC cells
          type: string
        url:
          description: A URL corresponding to this attribute
          example: https://www.ncbi.nlm.nih.gov/pubmed/29309293
          type: string
      type: object
    Feedback:
      description: A single unit of Feedback
      example:
        commenter_id: 1
        datetime: 2018-05-08 12:00
        rating_id: 1
        result_id: https://rtx.ncats.io/api/rtx/v1/result/234
        expertise_level_id: 1
        comment: This is a great result because...
        id: https://rtx.ncats.io/api/rtx/v1/result/234/feedback/56
        commenter_full_name: John Smith
      properties:
        id:
          description: URI for this feedback item
          example: https://rtx.ncats.io/api/rtx/v1/result/234/feedback/56
          type: string
        result_id:
          description: URI for the result that this feedback corresponds to
          example: https://rtx.ncats.io/api/rtx/v1/result/234
          type: string
        expertise_level_id:
          description: Integer identifier of the claimed expertise level
          example: 1
          type: integer
        rating_id:
          description: Integer identifier of the applied rating
          example: 1
          type: integer
        commenter_id:
          description: Integer identifier of the commenter
          example: 1
          type: integer
        commenter_full_name:
          description: Full name of the commenter
          example: John Smith
          type: string
        datetime:
          description: Datetime when the feedback was provided
          example: 2018-05-08 12:00
          type: string
        comment:
          description: A free text comment about this result
          example: This is a great result because...
          type: string
      type: object
      x-body-name: feedback
    ResultFeedback:
      description: Feedback for one result
      example:
        feedback_list:
        - commenter_id: 1
          datetime: 2018-05-08 12:00
          rating_id: 1
          result_id: https://rtx.ncats.io/api/rtx/v1/result/234
          expertise_level_id: 1
          comment: This is a great result because...
          id: https://rtx.ncats.io/api/rtx/v1/result/234/feedback/56
          commenter_full_name: John Smith
        - commenter_id: 1
          datetime: 2018-05-08 12:00
          rating_id: 1
          result_id: https://rtx.ncats.io/api/rtx/v1/result/234
          expertise_level_id: 1
          comment: This is a great result because...
          id: https://rtx.ncats.io/api/rtx/v1/result/234/feedback/56
          commenter_full_name: John Smith
      properties:
        feedback_list:
          description: List of feedback posts for this result
          items:
            $ref: '#/components/schemas/Feedback'
          type: array
      type: object
    MessageFeedback:
      description: Feedback for all the results corresponding to this message
      example:
        feedback_list:
        - commenter_id: 1
          datetime: 2018-05-08 12:00
          rating_id: 1
          result_id: https://rtx.ncats.io/api/rtx/v1/result/234
          expertise_level_id: 1
          comment: This is a great result because...
          id: https://rtx.ncats.io/api/rtx/v1/result/234/feedback/56
          commenter_full_name: John Smith
        - commenter_id: 1
          datetime: 2018-05-08 12:00
          rating_id: 1
          result_id: https://rtx.ncats.io/api/rtx/v1/result/234
          expertise_level_id: 1
          comment: This is a great result because...
          id: https://rtx.ncats.io/api/rtx/v1/result/234/feedback/56
          commenter_full_name: John Smith
      properties:
        feedback_list:
          description: List of feedback posts for this entire message
          items:
            $ref: '#/components/schemas/Feedback'
          type: array
      type: object
    Message_terms:
      description: Dict of terms needed by the specific query type
      example:
        anatomical_entity: liver
        disease: malaria
        metabolite: ibuprofen
        protein: P12345
        chemical_substance: ibuprofen
      properties:
        disease:
          example: malaria
          type: string
        protein:
          example: P12345
          type: string
        anatomical_entity:
          example: liver
          type: string
        chemical_substance:
          example: ibuprofen
          type: string
        metabolite:
          example: ibuprofen
          type: string
